name: stack-bump
version: '0.7.1.0'
category: Development
author: Pedro Tacla Yamada
synopsis: 'Dead simple version bumping for hpack packages'
description: '
Runs tests and build with stack, then bumps the package with a tagged commit.
'
maintainer: tacla.yamada@gmail.com
license: MIT
homepage: https://github.com/yamadapc/stack-bump

extra-source-files:
- ChangeLog.md

dependencies:
- base >=4.8 && <5
- optparse-applicative
- yaml
- lens
- lens-aeson
- text
- bytestring
- process
- strict
- async
- ansi-terminal
- Glob
- filepath

executables:
  stack-bump:
    main: Main.hs
    source-dirs: src

tests:
  hspec:
    main: Spec.hs
    source-dirs:
    - src
    - test
    dependencies:
    - hspec
    - QuickCheck
